name: Build & upload to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Decode google-services.json
        env:
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{ secrets.FIREBASE_OPTION }}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"  # or any other specific version if necessary

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2  # Updated version
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.APPID }}
            token: ${{ secrets.TOKEN }}
            groups: pre-tester  # Modify with your tester group
            file: build/app/outputs/apk/release/app-release.apk
